### ISSUE TITLE
Needs Tests

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/locationTrivia-API#1]

**Comment by JimCampagno** [comment]
Pull request will solve this issue.

**Comment by jmburges** [comment]
@JimCampagno you can mention a pull request like this. Resolved with #3

**Comment by jmburges** [comment]
@JimCampagno re-opening this because it's not complete!

**Comment by markedwardmurray** [comment]
@JimCampagno what's the status on this issue? I noticed that you pushed some new commits last week. Is it just pending review?

**Comment by AnnJohn** [comment]
Iceboxing the issue
