### ISSUE TITLE
tests import forecastr?

### ISSUE THREAD

**Issue by TOMalley104** [learn-co-curriculum/locationTrivia-API#5]
@JimCampagno

**Comment by JimCampagno** [comment]
Doesn't appear to be utilizing it.  @TOMalley104, want to take it out?

**Comment by TOMalley104** [comment]
![hell no](http://img-cache.cdn.gaiaonline.com/61a71edaa005c2463d768af8a106025e/http://i346.photobucket.com/albums/p421/man_rape/no_u.gif "No Jim, you do it.")

**Comment by JimCampagno** [comment]
:8ball: All good in the hood, removed it from the test file. :+1:
